name: Exemple de Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codi
        uses: actions/checkout@v3

      - name: Instal·lar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instal·lar dependències
        run: npm install

      - name: Executar tests
        run: npm test
